// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSfRNt653t0WWEJuFWO1WC5hJrkdbJRdg',
    appId: '1:605630567749:web:0a151a13b7e61df5f89a2c',
    messagingSenderId: '605630567749',
    projectId: 'code-brew-crew',
    authDomain: 'code-brew-crew.firebaseapp.com',
    databaseURL: 'https://code-brew-crew.firebaseio.com',
    storageBucket: 'code-brew-crew.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDw5mlrySLwF1aSntfm7IOImdBW7KPNoTg',
    appId: '1:605630567749:android:42f7712b6fd71baff89a2c',
    messagingSenderId: '605630567749',
    projectId: 'code-brew-crew',
    databaseURL: 'https://code-brew-crew.firebaseio.com',
    storageBucket: 'code-brew-crew.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwjaIXeZsOC9Uu1gfgU-jFHmdWepLUiUg',
    appId: '1:605630567749:ios:cf7b085101800aa0f89a2c',
    messagingSenderId: '605630567749',
    projectId: 'code-brew-crew',
    databaseURL: 'https://code-brew-crew.firebaseio.com',
    storageBucket: 'code-brew-crew.appspot.com',
    androidClientId: '605630567749-2fj984b8v1irs10ikmu3huviuj4cpfcg.apps.googleusercontent.com',
    iosClientId: '605630567749-fglf1uoaj8jge0n2v1mvrgfp56sm7ur6.apps.googleusercontent.com',
    iosBundleId: 'com.example.invoiceGenerator',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwjaIXeZsOC9Uu1gfgU-jFHmdWepLUiUg',
    appId: '1:605630567749:ios:cf7b085101800aa0f89a2c',
    messagingSenderId: '605630567749',
    projectId: 'code-brew-crew',
    databaseURL: 'https://code-brew-crew.firebaseio.com',
    storageBucket: 'code-brew-crew.appspot.com',
    androidClientId: '605630567749-2fj984b8v1irs10ikmu3huviuj4cpfcg.apps.googleusercontent.com',
    iosClientId: '605630567749-fglf1uoaj8jge0n2v1mvrgfp56sm7ur6.apps.googleusercontent.com',
    iosBundleId: 'com.example.invoiceGenerator',
  );
}
